### ISSUE TITLE
CM text uses outdated ABC channel identifier

### ISSUE THREAD

**Issue by hartman** [cmdotcom/text-sdk-dotnet#26]
https://github.com/cmdotcom/text-sdk-dotnet/blob/master/CM.Text/BusinessMessaging/Model/Channel.cs#L66

Seems that we still use iMessage here. At launch that was switched to "Apple Bussiness Chat", but it seems we never updated that here and still rely on the backwards compatibility support.

**Comment by mvesign** [comment]
Good find. Have added AppleBusinessChat to the Channel enum. And marked the enum value iMessage as obsolete. Changes are present in PR https://github.com/cmdotcom/text-sdk-dotnet/pull/34
