### ISSUE TITLE
Facebook Messenger support

### ISSUE THREAD

**Issue by Martijnvos** [cmdotcom/text-sdk-dotnet#27]
Is support for Facebook Messenger on the radar?

The [BM API supports it](https://www.cm.com/app/docs/en/api/business-messaging-api/1.0/index#facebook-messenger), although it doesn't seem to be a channel option in the Channels app as of yet.

**Comment by EricSmekens** [comment]
It is on the radar, and when Channels app is supporting this I think it should be included in here as well.
But I will accept any PR that includes Facebook Messenger support in this repository.
