### ISSUE TITLE
Add interface to TextClient class

### ISSUE THREAD

**Issue by StannieV** [cmdotcom/text-sdk-dotnet#7]
Greetings,

To make it possible to make a mock during unit testing, please add an interface to the TextClient class.

Thanks in advance,
Stan Verdiesen

**Comment by joepb** [comment]
Hi Stan,

Perhaps the best mockup would be using the Moq framework and inject a mocked HttpClient. The TextClient in itself is only a thin layer over the http connection and hardly adds any testable surface.
https://gingter.org/2018/07/26/how-to-mock-httpclient-in-your-net-c-unit-tests/

Cheers,

Joep
